from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Register_Contact_Dialog(object):
    def setupUi(self, Register_Contact_Dialog):
        Register_Contact_Dialog.setObjectName("Register_Contact_Dialog")
        Register_Contact_Dialog.resize(839, 702)
        self.label = QtWidgets.QLabel(Register_Contact_Dialog)
        self.label.setGeometry(QtCore.QRect(0, 10, 841, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Register_Contact_Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Register_Contact_Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 441, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Register_Contact_Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 230, 441, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Register_Contact_Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 380, 391, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Register_Contact_Dialog)
        self.label_6.setGeometry(QtCore.QRect(30, 400, 391, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Register_Contact_Dialog)
        self.label_7.setGeometry(QtCore.QRect(10, 630, 391, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.save_pushButton = QtWidgets.QPushButton(Register_Contact_Dialog)
        self.save_pushButton.setGeometry(QtCore.QRect(345, 650, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.save_pushButton.setFont(font)
        self.save_pushButton.setObjectName("save_pushButton")
        self.cancel_pushButton = QtWidgets.QPushButton(Register_Contact_Dialog)
        self.cancel_pushButton.setGeometry(QtCore.QRect(505, 650, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancel_pushButton.setFont(font)
        self.cancel_pushButton.setObjectName("cancel_pushButton")
        self.test_pushButton = QtWidgets.QPushButton(Register_Contact_Dialog)
        self.test_pushButton.setGeometry(QtCore.QRect(185, 650, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.test_pushButton.setFont(font)
        self.test_pushButton.setObjectName("test_pushButton")
        self.photo_FallAllert_label = QtWidgets.QLabel(Register_Contact_Dialog)
        self.photo_FallAllert_label.setGeometry(QtCore.QRect(30, 110, 301, 111))
        self.photo_FallAllert_label.setText("")
        self.photo_FallAllert_label.setPixmap(QtGui.QPixmap("FallAlertPythonBot_screenshot.jpeg"))
        self.photo_FallAllert_label.setScaledContents(True)
        self.photo_FallAllert_label.setObjectName("photo_FallAllert_label")
        self.label_8 = QtWidgets.QLabel(Register_Contact_Dialog)
        self.label_8.setGeometry(QtCore.QRect(30, 430, 251, 181))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("chat_id_screenshot.jpeg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.photo_FallAllert_label_2 = QtWidgets.QLabel(Register_Contact_Dialog)
        self.photo_FallAllert_label_2.setGeometry(QtCore.QRect(30, 260, 301, 111))
        self.photo_FallAllert_label_2.setText("")
        self.photo_FallAllert_label_2.setPixmap(QtGui.QPixmap("raw_info_bot_screenshot.jpeg"))
        self.photo_FallAllert_label_2.setScaledContents(True)
        self.photo_FallAllert_label_2.setObjectName("photo_FallAllert_label_2")

        self.retranslateUi(Register_Contact_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Register_Contact_Dialog)

    def retranslateUi(self, Register_Contact_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Register_Contact_Dialog.setWindowTitle(_translate("Register_Contact_Dialog", "Dialog"))
        self.label.setText(_translate("Register_Contact_Dialog", "Register Contact"))
        self.label_2.setText(_translate("Register_Contact_Dialog", "1. Open the Telegram app."))
        self.label_3.setText(_translate("Register_Contact_Dialog", "2. Search and start a conversation with @FallAlertPythonBot."))
        self.label_4.setText(_translate("Register_Contact_Dialog", "3. Search and start a conversation with @raw_info_bot."))
        self.label_5.setText(_translate("Register_Contact_Dialog", "4. Type the id that was sent to you as a response from "))
        self.label_6.setText(_translate("Register_Contact_Dialog", "@RawDataBot and test if you receive an alert."))
        self.label_7.setText(_translate("Register_Contact_Dialog", "5. Click on save."))
        self.save_pushButton.setText(_translate("Register_Contact_Dialog", "Save"))
        self.cancel_pushButton.setText(_translate("Register_Contact_Dialog", "Cancel"))
        self.test_pushButton.setText(_translate("Register_Contact_Dialog", "Test"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Register_Contact_Dialog = QtWidgets.QDialog()
    ui = Ui_Register_Contact_Dialog()
    ui.setupUi(Register_Contact_Dialog)
    Register_Contact_Dialog.show()
    sys.exit(app.exec_())
